#!/usr/bin/env python3
"""Reproduce the two Olympus cues from the exact user-selected performance.
Offline FFmpeg only. No further TTS service/model/telemetry calls.
The source WAV was generated by the official public Chatterbox demo; see docs/audio.
"""
from pathlib import Path
import hashlib,json,subprocess
ROOT=Path(__file__).resolve().parents[1];SOURCE=ROOT/'docs/audio/sources/olympus-selected-original.wav';DEST=ROOT/'public/audio/v3/voices/olympus'
DEST.mkdir(parents=True,exist_ok=True)
CUES=[('power','Behold my power!',0,1.78),('glory','Rise, and claim your glory!',1.78,4.04)]
records=[]
for key,text,start,end in CUES:
 dest=DEST/f'{key}.mp3'
 subprocess.run(['ffmpeg','-hide_banner','-loglevel','error','-y','-ss',str(start),'-i',str(SOURCE),'-t',str(end-start),'-af','highpass=f=70,loudnorm=I=-18:TP=-3:LRA=9','-ar','32000','-ac','1','-c:a','libmp3lame','-b:a','128k',str(dest)],check=True)
 info=json.loads(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','json',str(dest)]));duration=float(info['format']['duration'])
 records.append({'id':key,'text':text,'file':'voices/olympus/'+dest.name,'sourceRangeSeconds':[start,end],'durationSeconds':duration,'sha256':hashlib.sha256(dest.read_bytes()).hexdigest()})
 print(f'{key}: {duration:.2f}s',flush=True)
manifest={'engine':'Chatterbox English (official ResembleAI public demo)','modelLicense':'MIT','source':'https://huggingface.co/spaces/ResembleAI/Chatterbox','modelCard':'https://huggingface.co/ResembleAI/chatterbox','synthetic':True,'watermark':'Upstream PerTh embedded; no removal attempted. Detection after editing not independently verified.','selectedDirection':'User preferred expressive option 2 on 2026-10-08. Exact performance split, not regenerated.','sourceWavSha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),'originalText':'Behold my power! Rise, and claim your glory!','originalGeneration':{'referenceAudio':None,'exaggeration':1.25,'temperature':.8,'seed':4271,'cfgWeight':.3},'files':records}
(DEST.parent/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
